[package]
name = "calendar_app_bot"
version = "0.4.6"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calendar_app_lib = {path="../calendar_app_lib"}
anyhow = "1.0"
futures = "0.3"
tokio = {version="1.0", features=["full"]}
lazy_static = "1.4"
chrono = "0.4"
telegram-bot = {git = "https://github.com/ddboline/telegram-bot.git", tag="0.7.3"}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.2.0", features=["postgres_types"] }
