FROM rust_stable:latest
MAINTAINER Daniel Boline

WORKDIR /calendar_app_rust

ADD Cargo.toml /calendar_app_rust
ADD src /calendar_app_rust/src
ADD scripts /calendar_app_rust/scripts
ADD Makefile /calendar_app_rust
ADD templates /calendar_app_rust/templates
ADD calendar_app_lib /calendar_app_rust/calendar_app_lib
ADD calendar_app_http /calendar_app_rust/calendar_app_http
ADD gcal_lib /calendar_app_rust/gcal_lib
