[package]
name = "gcal_lib"
version = "0.1.7"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "1.0"
google-calendar3 = "1.0"
anyhow = "1.0"
retry = "1.0"
log = "0.4"
parking_lot = "0.10"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
chrono = "0.4"
