[package]
name = "gcal_lib"
version = "0.4.5"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper-rustls = "0.22"
hyper = { version = "0.14", features = ["stream"] }
anyhow = "1.0"
retry = "1.2"
log = "0.4"
parking_lot = "0.11"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"
env_logger = "0.8"
tokio = {version="1.0", features=["full"]}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.2.0", features=["diesel_types"] }
async-google-apis-common = { git = "https://github.com/ddboline/async-google-apis.git", branch="add_multithreaded_feature" }

[dev-dependencies]
calendar_app_lib = {path="../calendar_app_lib"}
