[package]
name = "calendar_app_lib"
version = "0.4.23"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
tokio-diesel = {git="https://github.com/mehcode/tokio-diesel.git", branch="master"}
reqwest = {version="0.11", default_features = false, features=["cookies", "json", "gzip", "rustls-tls"]}
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.5"
rayon = "1.5"
tokio = {version="1.9", features=["full"]}
url = "2.2"
dirs = "3.0"
dotenv = "0.15"
derive_more = "0.99"
serde = {version="1.0", features=["derive"]}
gcal_lib = {path="../gcal_lib"}
uuid = {version="0.8", features=["v4"]}
futures = "0.3"
select = "0.5"
structopt = "0.3"
itertools = "0.10"
blake3 = {version="1.0", features=["rayon"]}
hex = "0.4"
log = "0.4"
envy = "0.4"
smartstring = "0.2"
smallvec = "1.6"
serde_json = "1.0"
deadqueue = "0.2"
stack-string = { version="0.2", features=["diesel_types"] }
stdout-channel = "0.4"
