[package]
name = "calendar_app_lib"
version = "0.1.24"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
reqwest = {version="0.10", features=["cookies", "json"]}
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.5"
rayon = "1.3"
tokio = {version="0.2", features=["full"]}
url = "2.1"
dirs = "2.0"
dotenv = "0.15"
derive_more = "0.99"
serde = {version="1.0", features=["derive"]}
gcal_lib = {path="../gcal_lib"}
uuid = {version="0.8", features=["v4"]}
futures = "0.3"
select = "0.4"
structopt = "0.3"
itertools = "0.9"
blake3 = {version="0.2", features=["rayon"]}
hex = "0.4"
log = "0.4"
env_logger = "0.7"
inlinable_string = "0.1"
