[package]
name = "calendar_app_http"
version = "0.4.4"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calendar_app_lib = {path = "../calendar_app_lib"}
warp = "0.3"
http = "0.2"
chrono = "0.4"
chrono-tz = "0.5"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
tokio = {version="1.2", features=["time"]}
log = "0.4"
parking_lot = "0.11"
rayon = "1.5"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
dirs = "3.0"
itertools = "0.10"
url = "2.2"
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream"]}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.2.0", features=["diesel_types"] }
authorized_users = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.4.0"}

[dev-dependencies]
maplit = "1.0"
auth_server_http = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.4.0"}
auth_server_lib = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.4.0"}
