[package]
name = "calendar_app_http"
version = "0.6.4"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcal_lib = {path="../gcal_lib"}
calendar_app_lib = {path = "../calendar_app_lib"}
rweb = {version="0.15", features=["openapi", "chrono"], default-features=false}
http = "0.2"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
time-tz = {version="1.0", features=["system"]}
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
tokio = {version="1.17", features=["time"]}
log = "0.4"
parking_lot = "0.12"
rayon = "1.5"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
dirs = "4.0"
itertools = "0.10"
url = "2.2"
indexmap = "1.0"
derive_more = "0.99"
serde_yaml = "0.8"
uuid = "1.0"
rweb-helper = { git = "https://github.com/ddboline/rweb_helper.git", tag="0.4.12" }
reqwest = {version="0.11", default_features = false, features=["cookies", "json", "rustls-tls", "stream"]}
stack-string = { version="0.7", features=["postgres_types", "rweb-openapi"] }
authorized_users = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.8.3"}

[dev-dependencies]
maplit = "1.0"
auth_server_http = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.8.3"}
auth_server_lib = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.8.3"}
