[package]
name = "calendar_app_http"
version = "0.2.18"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0"
actix = "0.10"
actix-identity = "0.3"
actix-rt = "1.1"
calendar_app_lib = {path = "../calendar_app_lib"}
chrono = "0.4"
chrono-tz = "0.5"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
tokio = {version="0.2", features=["time"]}
log = "0.4"
parking_lot = "0.11"
maplit = "1.0"
rayon = "1.4"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
dirs = "3.0"
itertools = "0.9"
url = "2.1"
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"]}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.6", features=["diesel_types"] }
auth_server_rust = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.1.4"}
