[package]
name = "calendar_app_http"
version = "0.1.24"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix = "0.9"
actix-identity = "0.2"
actix-rt = "1.0"
calendar_app_lib = {path = "../calendar_app_lib"}
chrono = "0.4"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
tokio = {version="0.2", features=["time"]}
log = "0.4"
parking_lot = "0.10"
maplit = "1.0"
rayon = "1.3"
walkdir = "2.3"
anyhow = "1.0"
thiserror = "1.0"
rust_auth_server = { git = "https://github.com/ddboline/rust-auth-server.git", tag="0.5.10" }
async-trait = "0.1"
dirs = "2.0"
itertools = "0.9"
url = "2.1"
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"]}
