openapi: 3.0.1
info:
  title: Calendar Web App
  description: Web App to Display Calendar, Sync with GCal
  version: 0.7.16
paths:
  /calendar/index.html:
    get:
      description: Calendar App Main Page
      responses:
        '200':
          description: Main Page
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/agenda:
    get:
      description: Calendar Agenda Page
      responses:
        '200':
          description: Agenda
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/sync_calendars:
    post:
      description: Sync Calendars
      responses:
        '200':
          description: Sync Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/sync_calendars_full:
    post:
      description: Fully Sync All Calendars
      responses:
        '200':
          description: Sync Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/delete_event:
    delete:
      description: Delete Calendar Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GcalEventID'
        required: true
      responses:
        '204':
          description: Delete Event Output
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/list_calendars:
    get:
      description: List Calendars
      responses:
        '200':
          description: List Calendars
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/list_events:
    get:
      description: List Events
      parameters:
      - name: calendar_name
        in: query
        required: true
        schema:
          description: Calendar Name
          type: string
      - name: min_time
        in: query
        required: false
        schema:
          description: Earliest Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      - name: max_time
        in: query
        required: false
        schema:
          description: Latest Date
          format: date
          nullable: true
          example: 2023-01-01
          type: string
      responses:
        '200':
          description: List Events
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/event_detail:
    get:
      description: Get Calendar Event Detail
      parameters:
      - name: gcal_id
        in: query
        required: true
        schema:
          description: GCal ID
          type: string
      - name: event_id
        in: query
        required: true
        schema:
          description: GCal Event ID
          type: string
      responses:
        '201':
          description: Event Details
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/calendar_list:
    get:
      description: List Calendars
      parameters:
      - name: min_modified
        in: query
        required: false
        schema:
          description: Min Modified Date
          format: date-time
          nullable: true
          type: string
      responses:
        '200':
          description: Calendar List
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CalendarList'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
    post:
      description: Update Calendars
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarUpdateRequest'
        required: true
      responses:
        '201':
          description: Calendar List Update
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CalendarList'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/calendar_cache:
    get:
      description: List Recent Calendar Events
      parameters:
      - name: min_modified
        in: query
        required: false
        schema:
          description: Min Modified Date
          format: date-time
          nullable: true
          type: string
      responses:
        '200':
          description: Calendar Cache
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CalendarCache'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
    post:
      description: Update Calendar Events
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarCacheUpdateRequest'
        required: true
      responses:
        '201':
          description: Calendar Cache Update
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CalendarCache'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/user:
    get:
      responses:
        '200':
          description: Logged in User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggedUser'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/link/{link}:
    get:
      description: Get Full URL from Shortened URL
      parameters:
      - name: link
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Shortened Link
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/create_calendar_event:
    get:
      description: Get Calendar Event Creation Form
      parameters:
      - name: gcal_id
        in: query
        required: true
        schema:
          description: GCal Calendar ID
          type: string
      - name: event_id
        in: query
        required: false
        schema:
          description: Event ID
          nullable: true
          type: string
      responses:
        '200':
          description: Build Calendar Event
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
    post:
      description: Create Calendar Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCalendarEventRequest'
        required: true
      responses:
        '201':
          description: Create Calendar Event
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
  /calendar/edit_calendar/{gcal_id}:
    post:
      description: Edit Google Calendar Event
      parameters:
      - name: gcal_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                calendar_name:
                  description: Calendar Name
                  nullable: true
                  type: string
                sync:
                  description: Sync Flag
                  nullable: true
                  type: boolean
                edit:
                  description: Edit Flag
                  nullable: true
                  type: boolean
                display:
                  description: Display Flag
                  nullable: true
                  type: boolean
              type: object
        required: true
      responses:
        '200':
          description: Edit Calendar Event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarList'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
components:
  schemas:
    GcalEventID:
      properties:
        gcal_id:
          description: GCal ID
          type: string
        event_id:
          description: GCal Event ID
          type: string
      type: object
      required:
      - gcal_id
      - event_id
    CalendarList:
      properties:
        calendar_name:
          description: Calendar Name
          type: string
        gcal_id:
          description: GCal Calendar ID
          type: string
        gcal_name:
          description: GCal Calendar Name
          nullable: true
          type: string
        gcal_description:
          description: GCal Calendar Description
          nullable: true
          type: string
        gcal_location:
          description: GCal Calendar Location
          nullable: true
          type: string
        gcal_timezone:
          description: GCal Calendar Timezone
          nullable: true
          type: string
        sync:
          description: Sync Flag
          type: boolean
        last_modified:
          description: Last Modified
          format: date-time
          type: string
        edit:
          description: Edit Flag
          type: boolean
        display:
          description: Display Flag
          type: boolean
      type: object
      required:
      - calendar_name
      - gcal_id
      - sync
      - last_modified
      - edit
      - display
    CalendarUpdateRequest:
      properties:
        updates:
          description: Calendar List Updates
          items:
            $ref: '#/components/schemas/CalendarList'
          type: array
      type: object
      required:
      - updates
    CalendarCache:
      properties:
        gcal_id:
          description: Gcal Calendar ID
          type: string
        event_id:
          description: Calendar Event ID
          type: string
        event_start_time:
          description: Event Start Time
          format: date-time
          type: string
        event_end_time:
          description: Event End Time
          format: date-time
          type: string
        event_url:
          description: Event URL
          nullable: true
          type: string
        event_name:
          description: Event Name
          type: string
        event_description:
          description: Event Description
          nullable: true
          type: string
        event_location_name:
          description: Event Location Name
          nullable: true
          type: string
        event_location_lat:
          description: Event Location Latitude
          nullable: true
          type: number
        event_location_lon:
          description: Event Location Longitude
          nullable: true
          type: number
        last_modified:
          description: Last Modified
          format: date-time
          type: string
      type: object
      required:
      - gcal_id
      - event_id
      - event_start_time
      - event_end_time
      - event_name
      - last_modified
    CalendarCacheUpdateRequest:
      properties:
        updates:
          description: Calendar Events Update
          items:
            $ref: '#/components/schemas/CalendarCacheRequest'
          type: array
      type: object
      required:
      - updates
    CalendarCacheRequest:
      properties:
        gcal_id:
          description: GCal Calendar ID
          type: string
        event_id:
          description: Calendar Event ID
          type: string
        event_start_time:
          description: Event Start Time
          format: date-time
          type: string
        event_end_time:
          description: Event End Time
          format: date-time
          type: string
        event_url:
          description: Event URL
          nullable: true
          type: string
        event_name:
          description: Event Name
          type: string
        event_description:
          description: Event Description
          nullable: true
          type: string
        event_location_name:
          description: Event Location Name
          nullable: true
          type: string
        event_location_lat:
          description: Event Location Latitude
          nullable: true
          type: number
        event_location_lon:
          description: Event Location Longitude
          nullable: true
          type: number
        last_modified:
          description: Last Modified
          format: date-time
          type: string
      type: object
      required:
      - gcal_id
      - event_id
      - event_start_time
      - event_end_time
      - event_name
      - last_modified
    LoggedUser:
      properties:
        email:
          description: Email Address
          type: string
        session:
          description: Session Id
          format: uuid
          example: 334518f4-1bfd-4f20-9978-bfad0dc033e1
          type: string
        secret_key:
          description: Secret Key
          type: string
      type: object
      required:
      - email
      - session
      - secret_key
    CreateCalendarEventRequest:
      properties:
        gcal_id:
          description: GCal Calendar ID
          type: string
        event_id:
          description: Event ID
          type: string
        event_start_datetime:
          description: Event Start Time
          format: date-time
          type: string
        event_end_datetime:
          description: Event End Time
          format: date-time
          type: string
        event_url:
          description: Event URL
          nullable: true
          type: string
        event_name:
          description: Event Name
          type: string
        event_description:
          description: Event Description
          nullable: true
          type: string
        event_location_name:
          description: Event Location Name
          nullable: true
          type: string
      type: object
      required:
      - gcal_id
      - event_id
      - event_start_datetime
      - event_end_datetime
      - event_name
