name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12.4-alpine
        env:
          POSTGRES_DB: calendar_app_cache
          POSTGRES_PASSWORD: 2UtcMAAvNuBHPqK9
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update && \
        sudo apt-get install libpq-dev && \
        rustup update && \
        cargo install diesel_cli

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic

    - name: Build
      run: cargo build --verbose

    - name: Run tests / generate coverage report
      run: |
        mkdir -p ${HOME}/.config/calendar_app_rust ${HOME}/.gcal && \
        echo ${{secrets.CLIENT_SECRETS_JSON}} > ${HOME}/.config/calendar_app_rust/client_secrets.json && \
        echo ${{secrets.DDBOLINE_AT_GMAIL_COM_JSON}} > ${HOME}/.gcal/ddboline@gmail.com && \
        diesel database setup && \
        cargo test --all --verbose && \
        cargo install cargo-tarpaulin && \
        cargo tarpaulin --verbose --all-features --workspace --out Xml
      env:
        DATABASE_URL: postgresql://postgres:2UtcMAAvNuBHPqK9@localhost:5432/calendar_app_cache
        GCAL_SECRET_FILE: ${HOME}/.config/calendar_app_rust/client_secrets.json
        GCAL_TOKEN_PATH: ${HOME}/.gcal

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
